services:
  db:
    image: postgres:16.9-bullseye
    container_name: postgres_db
    restart: on-failure
    env_file: ".env"
    ports:
      - "5432:5432"
    networks:
      - main

networks:
  main:
    name: main_network
    driver: bridge
